// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Existing sidebar for general documentation
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar for Embedded
  embeddedSidebar: [{type: 'autogenerated', dirName: 'embedded'}],

  // Sidebar for UnifiedAPI
  unifiedApiSidebar: [{type: 'autogenerated', dirName: 'unifiedapi'}],
};

export default sidebars;
